### ISSUE TITLE
Support for multiple X32s

### ISSUE THREAD

**Issue by wlabarron** [ents-crew/x32-reflector#2]
The ability to specify more than one X32 IP address in the config file, to support venues with multiple boards.

**Comment by Vitineth** [comment]
Addressed on https://github.com/ents-crew/x32-reflector/tree/feature/multi-x32
Should be ready for a production test - will upload new version for testing on Wednesday during training

**Comment by Vitineth** [comment]
Feedback on UI/UX is welchttps://github.com/ents-crew/x32-reflector/tree/feature/multi-x32omed. Example instance shown below

![image](https://user-images.githubusercontent.com/9435503/161799830-ab6d5864-a4cd-43bb-abf2-c8c32ec06ea6.png)

**Comment by wlabarron** [comment]
Could the config file specify a name for each X32 device, so that the UI can say "X32" and "X32 Compact" or similar instead of primary/secondary?

**Comment by Vitineth** [comment]
Merged with #8
