### ISSUE TITLE
Adjust config page refresh rate

### ISSUE THREAD

**Issue by wlabarron** [ents-crew/x32-reflector#4]
The config page currently refreshes every few seconds. This makes filling in the form difficult, as it disappears while you fill it in.

**Comment by Vitineth** [comment]
Addressed in https://github.com/ents-crew/x32-reflector/tree/feature/timeout
Timeout default changed to 90 seconds with animated monitor and when JS is enabled it will prevent reloading while form is focused. Needs testing

**Comment by Vitineth** [comment]
Merged with #8
